export const inputsList = {
    EMAIL: "email",
    TEXT: "text",
    PASSWORD: "password",
};

export const iconsList = {
    INFO: "info",
    CLOSE: "close",
    ARROW_DOWN: "arrow_down",
    ARROW_UP: "arrow_up",
    ARROW_RIGHT: "arrow_right",
    ARROW_LEFT: "arrow_left",
    SETINGS: "settings",
    DELETE: "delete",
    DONE: "done",
    DONE_CIRCLE: "done_circle",
    PLUS: "plus",
    PROFILE: "profile",
    PHONE: "phone",
    SAVE: "save",
    ALERT: "alert",
    ENTER: "enter",
    ARROW_2_RIGHT: "arrow_2_right",
    MENU: "menu",
    MENU_SELECTED: "menu_selected",
    EDIT: "edit",
    SHARE: "share",
    CHECKBOX_ON: "checkbox_on",
    CHECKBOX_OFF: "checkbox_off",
    DOWNLOAD: "download",
    EXTERNAL_LINK: "external_link",
    HOME: "home",
    LESS: "less",
    LOCATION: "location",
    CIRCLE_CHECK: "circle_check",
    CIRCLE_CHECK_FILLED: "circle_check_filled",
    LOGOUT: "logout",
    EYE: "eye",
    EYE_SELECTED: "eye_selected",
    EVENT: "event",
    SEARCH: "search",
    ADMIN: "admin",
    ACCIDENT: "accident",
    LIFE: "life",
    CARS: "cars",
    DAMAGES: "damages",
    COTIZAR: "cotizar", 
    EMISION: "emision",
    CONSULTAS: "consultas",
    SUSCRIPCIONES: "suscripciones",
    MODULO: "modulo",
    CALENDARIO: "calendario",
    REPORTES: "reportes",
    HORA: "hora",
    USER_PEAK: "user_peak",
}

export const buttonsList = {
    PRINCIPAL_BUTTON: "principal_button",
}
